import unittest
from unittest.mock import patch
from urllib.error import URLError

from tools import mock_store
from tools.build_checker import check_repo_health, merge_repo_health_scaffold
from tools.github_tool import GitHubConfig, GitHubClient, check_github_auth, commit_files, create_repo
from tools.repo_writer import append_build_log
from tools.verifier import verify_commit


class Person3GitHubToolTests(unittest.TestCase):
    def setUp(self):
        mock_store.reset_mock_store()

    def test_config_reads_mock_mode(self):
        with patch.dict(
            "os.environ",
            {
                "GITHUB_TOKEN": "secret-token",
                "GITHUB_OWNER": "demo-owner",
                "GITHUB_REPO_PREFIX": "mvpilot-generated-",
                "MVPILOT_MOCK_TOOLS": "true",
            },
            clear=True,
        ):
            config = GitHubConfig.from_env()

        self.assertEqual(config.token, "secret-token")
        self.assertEqual(config.owner, "demo-owner")
        self.assertTrue(config.mock_tools)

    def test_client_refuses_live_request_without_token(self):
        client = GitHubClient(GitHubConfig(token=None, owner="owner", repo_prefix="mvpilot-generated-", mock_tools=False))

        with self.assertRaises(RuntimeError):
            client.get_authenticated_user()

    def test_client_uses_certifi_ssl_context_for_live_requests(self):
        captured: dict[str, object] = {}

        def fake_urlopen(request, timeout=20, context=None):
            captured["context"] = context
            raise URLError("stop")

        client = GitHubClient(
            GitHubConfig(
                token="secret-token",
                owner="owner",
                repo_prefix="mvpilot-generated-",
                mock_tools=False,
            )
        )
        with patch("tools.github_tool.urlopen", fake_urlopen):
            with self.assertRaises(RuntimeError):
                client.get_authenticated_user()

        self.assertIsNotNone(captured.get("context"))

    def test_create_repo_uses_mock_mode_without_credentials(self):
        with patch.dict(
            "os.environ",
            {
                "GITHUB_OWNER": "demo-owner",
                "GITHUB_REPO_PREFIX": "mvpilot-generated-",
                "MVPILOT_MOCK_TOOLS": "true",
            },
            clear=True,
        ):
            result = create_repo(
                "mvpilot-generated-referral-agent",
                "Generated by MVPilot",
                "public",
            )

        self.assertEqual(result["tool_name"], "github.create_repo")
        self.assertEqual(result["status"], "mock")
        self.assertEqual(result["verification_status"], "mock")
        self.assertEqual(result["output"]["repo_name"], "mvpilot-generated-referral-agent")

    def test_create_repo_uses_supplied_task_config_instead_of_env(self):
        config = GitHubConfig(
            token="task-token",
            owner="connected-owner",
            repo_prefix="mvpilot-generated-",
            mock_tools=False,
        )
        with (
            patch.dict(
                "os.environ",
                {
                    "GITHUB_TOKEN": "env-token",
                    "GITHUB_OWNER": "env-owner",
                    "MVPILOT_MOCK_TOOLS": "false",
                },
                clear=True,
            ),
            patch("tools.github_tool.GitHubClient") as client_class,
        ):
            client = client_class.return_value
            client.get_repo.side_effect = lambda name: {
                "html_url": f"https://github.com/connected-owner/{name}",
                "full_name": f"connected-owner/{name}",
            }
            client.create_user_repo.return_value = {
                "html_url": "https://github.com/connected-owner/mvpilot-generated-demo",
                "id": 123,
            }

            result = create_repo(
                "mvpilot-generated-demo",
                "Generated by MVPilot",
                "public",
                config=config,
                reuse_existing=False,
            )

        self.assertEqual(result["status"], "success")
        client_class.assert_called_once_with(config)
        client.create_user_repo.assert_called_once_with(
            "mvpilot-generated-demo",
            "Generated by MVPilot",
            private=False,
        )
        self.assertEqual(
            result["output"]["verified_full_name"],
            "connected-owner/mvpilot-generated-demo",
        )

    def test_check_github_auth_uses_mock_mode(self):
        with patch.dict(
            "os.environ",
            {
                "GITHUB_OWNER": "demo-owner",
                "MVPILOT_MOCK_TOOLS": "true",
            },
            clear=True,
        ):
            result = check_github_auth()

        self.assertEqual(result["tool_name"], "github.check_auth")
        self.assertEqual(result["status"], "mock")
        self.assertEqual(result["verification_status"], "mock")

    def test_check_github_auth_requires_token_in_live_mode(self):
        with patch.dict(
            "os.environ",
            {
                "GITHUB_OWNER": "demo-owner",
                "MVPILOT_MOCK_TOOLS": "false",
            },
            clear=True,
        ):
            result = check_github_auth()

        self.assertEqual(result["tool_name"], "github.check_auth")
        self.assertEqual(result["status"], "failed")
        self.assertIn("GITHUB_TOKEN", result["error"])

    def test_create_repo_reuses_existing_repository(self):
        config = GitHubConfig(
            token="task-token",
            owner="connected-owner",
            repo_prefix="mvpilot-generated-",
            mock_tools=False,
        )
        with patch("tools.github_tool.GitHubClient") as client_class:
            client = client_class.return_value
            client.get_repo.return_value = {
                "html_url": "https://github.com/connected-owner/mvpilot-generated-studypilot",
                "full_name": "connected-owner/mvpilot-generated-studypilot",
            }

            result = create_repo(
                "mvpilot-generated-studypilot",
                "Generated by MVPilot",
                "private",
                config=config,
                task_id="task-abc123",
            )

        self.assertEqual(result["status"], "success")
        self.assertEqual(result["output"]["status"], "reused")
        client.create_user_repo.assert_not_called()

    def test_create_repo_retries_with_unique_suffix_on_name_conflict(self):
        config = GitHubConfig(
            token="task-token",
            owner="connected-owner",
            repo_prefix="mvpilot-generated-",
            mock_tools=False,
        )
        conflict = RuntimeError(
            'GitHub API HTTP 422: {"message":"Repository creation failed.",'
            '"errors":[{"message":"name already exists on this account"}]}'
        )

        with patch("tools.github_tool.GitHubClient") as client_class:
            client = client_class.return_value
            created_name = "mvpilot-generated-studypilot-taskab"

            def create_side_effect(name: str, description: str, private: bool) -> dict:
                del description, private
                if name == "mvpilot-generated-studypilot":
                    raise conflict
                return {
                    "html_url": f"https://github.com/connected-owner/{name}",
                    "id": 9,
                }

            def get_repo_side_effect(name: str) -> dict:
                if name == created_name:
                    return {
                        "html_url": f"https://github.com/connected-owner/{name}",
                        "full_name": f"connected-owner/{name}",
                    }
                raise RuntimeError("GitHub API HTTP 404: not found")

            client.create_user_repo.side_effect = create_side_effect
            client.get_repo.side_effect = get_repo_side_effect

            result = create_repo(
                "mvpilot-generated-studypilot",
                "Generated by MVPilot",
                "private",
                config=config,
                task_id="task-abc123",
                reuse_existing=False,
            )

        self.assertEqual(result["status"], "success")
        self.assertEqual(result["output"]["repo_name"], created_name)
        self.assertTrue(result["output"]["name_adjusted"])

    def test_create_repo_refuses_non_generated_repo(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = create_repo("MVPilot", "Wrong repo", "public")

        self.assertEqual(result["status"], "refused")
        self.assertIn("mvpilot-generated-", result["error"])

    def test_create_repo_rejects_invalid_visibility(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = create_repo("mvpilot-generated-demo", "Demo", "internal")

        self.assertEqual(result["status"], "failed")
        self.assertIn("validation_error", result["output"])

    def test_commit_files_uses_mock_mode(self):
        with patch.dict(
            "os.environ",
            {
                "GITHUB_OWNER": "demo-owner",
                "MVPILOT_MOCK_TOOLS": "true",
            },
            clear=True,
        ):
            result = commit_files(
                "mvpilot-generated-referral-agent",
                [
                    {"path": "README.md", "content": "# Demo"},
                    {"path": "logs/build_log.md", "content": "Started"},
                ],
                "Add initial scaffold",
            )

        self.assertEqual(result["tool_name"], "github.commit_files")
        self.assertEqual(result["status"], "mock")
        self.assertEqual(result["verification_status"], "mock")
        self.assertEqual(result["output"]["files_changed"], 2)
        self.assertEqual(result["output"]["changed_files"], ["README.md", "logs/build_log.md"])

    def test_commit_files_uses_supplied_task_config_for_commit_and_verification(self):
        config = GitHubConfig(
            token="task-token",
            owner="connected-owner",
            repo_prefix="mvpilot-generated-",
            mock_tools=False,
        )
        with (
            patch.dict(
                "os.environ",
                {
                    "GITHUB_TOKEN": "env-token",
                    "GITHUB_OWNER": "env-owner",
                    "MVPILOT_MOCK_TOOLS": "false",
                },
                clear=True,
            ),
            patch("tools.github_tool.GitHubClient") as client_class,
            patch("tools.verifier.verify_commit") as verify_mock,
        ):
            client = client_class.return_value
            client.get_repo.return_value = {"default_branch": "main"}
            client.get_ref.return_value = {"object": {"sha": "parent-sha"}}
            client.get_commit.return_value = {"commit": {"tree": {"sha": "tree-sha"}}}
            client.create_blob.return_value = {"sha": "blob-sha"}
            client.create_tree.return_value = {"sha": "new-tree-sha"}
            client.create_commit.return_value = {"sha": "new-commit-sha"}
            verify_mock.return_value = {
                "tool_name": "github.verify_commit",
                "status": "success",
                "verification_status": "verified",
                "output": {"commit_sha": "new-commit-sha"},
                "error": None,
            }

            result = commit_files(
                "mvpilot-generated-demo",
                [{"path": "README.md", "content": "# Demo"}],
                "Add README",
                config=config,
            )

        self.assertEqual(result["status"], "success")
        client_class.assert_called_once_with(config)
        verify_mock.assert_called_once_with(
            "mvpilot-generated-demo",
            "new-commit-sha",
            config=config,
            allow_existing_repo=False,
        )

    def test_commit_files_seeds_initial_commit_for_empty_repository(self):
        config = GitHubConfig(
            token="task-token",
            owner="connected-owner",
            repo_prefix="mvpilot-generated-",
            mock_tools=False,
        )
        with (
            patch.dict(
                "os.environ",
                {
                    "GITHUB_TOKEN": "env-token",
                    "GITHUB_OWNER": "env-owner",
                    "MVPILOT_MOCK_TOOLS": "false",
                },
                clear=True,
            ),
            patch("tools.github_tool.GitHubClient") as client_class,
            patch("tools.verifier.verify_commit") as verify_mock,
        ):
            client = client_class.return_value
            client.get_repo.return_value = {"default_branch": "main", "size": 0}
            client.get_ref.side_effect = RuntimeError(
                'GitHub API HTTP 409: {"message": "Git Repository is empty."}'
            )
            client.get_contents_sha.return_value = None
            client.put_contents.return_value = {"commit": {"sha": "seed-commit-sha"}}
            verify_mock.return_value = {
                "tool_name": "github.verify_commit",
                "status": "success",
                "verification_status": "verified",
                "output": {"commit_sha": "seed-commit-sha"},
                "error": None,
            }

            result = commit_files(
                "my-existing-repo",
                [{"path": "README.md", "content": "# Demo"}],
                "Add generated MVPilot package",
                config=config,
                allow_existing_repo=True,
            )

        self.assertEqual(result["status"], "success")
        client.put_contents.assert_called_once()
        client.get_ref.assert_called_once()
        client.create_ref.assert_not_called()

    def test_commit_files_uses_tree_api_when_ref_exists_even_if_repo_size_is_zero(self):
        """auto_init repos can report size=0 while README already exists on the default branch."""

        config = GitHubConfig(
            token="task-token",
            owner="connected-owner",
            repo_prefix="mvpilot-generated-",
            mock_tools=False,
        )
        with (
            patch.dict(
                "os.environ",
                {
                    "GITHUB_TOKEN": "env-token",
                    "GITHUB_OWNER": "env-owner",
                    "MVPILOT_MOCK_TOOLS": "false",
                },
                clear=True,
            ),
            patch("tools.github_tool.GitHubClient") as client_class,
            patch("tools.verifier.verify_commit") as verify_mock,
        ):
            client = client_class.return_value
            client.get_repo.return_value = {"default_branch": "main", "size": 0}
            client.get_ref.return_value = {"object": {"sha": "parent-sha"}}
            client.get_commit.return_value = {"commit": {"tree": {"sha": "tree-sha"}}}
            client.create_blob.return_value = {"sha": "blob-sha"}
            client.create_tree.return_value = {"sha": "new-tree-sha"}
            client.create_commit.return_value = {"sha": "new-commit-sha"}
            verify_mock.return_value = {
                "tool_name": "github.verify_commit",
                "status": "success",
                "verification_status": "verified",
                "output": {"commit_sha": "new-commit-sha"},
                "error": None,
            }

            result = commit_files(
                "mvpilot-generated-demo",
                [{"path": "README.md", "content": "# Demo"}],
                "Add README",
                config=config,
            )

        self.assertEqual(result["status"], "success")
        client.put_contents.assert_not_called()
        client.create_tree.assert_called_once()

    def test_commit_files_rejects_empty_file_list(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = commit_files("mvpilot-generated-demo", [], "Empty commit")

        self.assertEqual(result["status"], "failed")
        self.assertIn("validation_error", result["output"])

    def test_commit_files_rejects_unsafe_path(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = commit_files(
                "mvpilot-generated-demo",
                [{"path": "../secret.txt", "content": "bad"}],
                "Bad commit",
            )

        self.assertEqual(result["status"], "failed")
        self.assertIn("validation_error", result["output"])

    def test_verify_commit_accepts_mock_sha(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            commit_result = commit_files(
                "mvpilot-generated-demo",
                [{"path": "README.md", "content": "# Demo"}],
                "Add README",
            )
            result = verify_commit("mvpilot-generated-demo", commit_result["output"]["commit_sha"])

        self.assertEqual(result["tool_name"], "github.verify_commit")
        self.assertEqual(result["status"], "mock")
        self.assertTrue(result["output"]["verified"])
        self.assertEqual(result["output"]["files_changed"], ["README.md"])

    def test_verify_commit_uses_supplied_task_config(self):
        config = GitHubConfig(
            token="task-token",
            owner="connected-owner",
            repo_prefix="mvpilot-generated-",
            mock_tools=False,
        )
        with (
            patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True),
            patch("tools.verifier.GitHubClient") as client_class,
        ):
            client = client_class.return_value
            client.get_commit.return_value = {
                "sha": "abc123",
                "files": [{"filename": "README.md"}],
            }

            result = verify_commit("mvpilot-generated-demo", "abc123", config=config)

        self.assertEqual(result["status"], "success")
        client_class.assert_called_once_with(config)
        self.assertEqual(result["output"]["files_changed"], ["README.md"])

    def test_verify_commit_rejects_fake_live_shape_in_mock_mode(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = verify_commit("mvpilot-generated-demo", "abc123")

        self.assertEqual(result["status"], "failed")
        self.assertEqual(result["verification_status"], "failed")

    def test_verify_commit_rejects_empty_sha(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = verify_commit("mvpilot-generated-demo", " ")

        self.assertEqual(result["status"], "failed")
        self.assertIn("must not be empty", result["error"])

    def test_append_build_log_preserves_previous_entries(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            first = append_build_log("task-1", "mvpilot-generated-demo", "Created repo", {"step": 1})
            second = append_build_log("task-1", "mvpilot-generated-demo", "Committed files", {"step": 2})
            content = mock_store.get_file("mvpilot-generated-demo", "logs/build_log.md")

        self.assertEqual(first["status"], "mock")
        self.assertEqual(second["status"], "mock")
        self.assertIn("Created repo", content)
        self.assertIn("Committed files", content)

    def test_append_build_log_rejects_empty_message(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = append_build_log("task-1", "mvpilot-generated-demo", " ", {})

        self.assertEqual(result["status"], "failed")
        self.assertIn("message must not be empty", result["error"])

    def test_append_build_log_retries_once_on_live_commit_failure(self):
        with (
            patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "false", "GITHUB_TOKEN": "token", "GITHUB_OWNER": "owner"}, clear=True),
            patch("tools.repo_writer.GitHubClient") as client_class,
            patch("tools.repo_writer.commit_files") as commit_files_mock,
            patch("tools.repo_writer._format_log_entry", return_value="- fixed | task=task-1 | Committed files\n"),
        ):
            client = client_class.return_value
            client.get_file_text.return_value = "# MVPilot Build Log\n\n"
            commit_files_mock.side_effect = [
                {
                    "tool_name": "github.commit_files",
                    "status": "failed",
                    "verification_status": "failed",
                    "output": {},
                    "error": "simulated conflict",
                },
                {
                    "tool_name": "github.commit_files",
                    "status": "success",
                    "verification_status": "verified",
                    "output": {"commit_sha": "abc123"},
                    "error": None,
                },
            ]
            client.get_file_text.side_effect = [
                "# MVPilot Build Log\n\n",
                "# MVPilot Build Log\n\n",
                "# MVPilot Build Log\n\n- fixed | task=task-1 | Committed files\n",
            ]

            result = append_build_log("task-1", "mvpilot-generated-demo", "Committed files", {})

        self.assertEqual(result["status"], "success")
        self.assertEqual(result["output"]["attempts"], 2)
        self.assertEqual(commit_files_mock.call_count, 2)

    def test_append_build_log_polls_after_live_commit_before_failing_verification(self):
        with (
            patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "false", "GITHUB_TOKEN": "token", "GITHUB_OWNER": "owner"}, clear=True),
            patch("tools.repo_writer.GitHubClient") as client_class,
            patch("tools.repo_writer.commit_files") as commit_files_mock,
            patch("tools.repo_writer.sleep") as sleep_mock,
            patch("tools.repo_writer._format_log_entry", return_value="- fixed | task=task-1 | Committed files\n"),
        ):
            client = client_class.return_value
            commit_files_mock.return_value = {
                "tool_name": "github.commit_files",
                "status": "success",
                "verification_status": "verified",
                "output": {"commit_sha": "abc123"},
                "error": None,
            }
            client.get_file_text.side_effect = [
                "# MVPilot Build Log\n\n",
                "# MVPilot Build Log\n\n",
                "# MVPilot Build Log\n\n- fixed | task=task-1 | Committed files\n",
            ]

            result = append_build_log("task-1", "mvpilot-generated-demo", "Committed files", {})

        self.assertEqual(result["status"], "success")
        self.assertEqual(result["output"]["attempts"], 1)
        self.assertEqual(result["output"]["verification_attempts"], 2)
        self.assertEqual(commit_files_mock.call_count, 1)
        sleep_mock.assert_called_once()

    def test_append_build_log_accepts_verified_commit_when_contents_api_lags(self):
        with (
            patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "false", "GITHUB_TOKEN": "token", "GITHUB_OWNER": "owner"}, clear=True),
            patch("tools.repo_writer.GitHubClient") as client_class,
            patch("tools.repo_writer.commit_files") as commit_files_mock,
            patch("tools.repo_writer.verify_commit") as verify_commit_mock,
            patch("tools.repo_writer.sleep"),
            patch("tools.repo_writer._format_log_entry", return_value="- fixed | task=task-1 | Committed files\n"),
        ):
            client = client_class.return_value
            commit_files_mock.return_value = {
                "tool_name": "github.commit_files",
                "status": "success",
                "verification_status": "verified",
                "output": {"commit_sha": "abc123"},
                "error": None,
            }
            client.get_file_text.return_value = "# MVPilot Build Log\n\n"
            verify_commit_mock.return_value = {
                "tool_name": "github.verify_commit",
                "status": "success",
                "verification_status": "verified",
                "output": {"commit_sha": "abc123", "files_changed": ["logs/build_log.md"]},
                "error": None,
            }

            result = append_build_log("task-1", "mvpilot-generated-demo", "Committed files", {})

        self.assertEqual(result["status"], "success")
        self.assertTrue(result["output"]["verified"])
        self.assertFalse(result["output"]["content_verified"])
        self.assertTrue(result["output"]["commit_verified"])
        self.assertEqual(result["output"]["verification_method"], "commit")

    def test_merge_repo_health_scaffold_adds_missing_package_and_source_files(self):
        merged = merge_repo_health_scaffold(
            [
                {"path": "README.md", "content": "# Demo"},
                {"path": "docs/BUILD_LOG.md", "content": "# Log"},
                {"path": "docs/ARCHITECTURE.md", "content": "# Architecture"},
                {"path": "demo/demo_script.md", "content": "Demo"},
            ]
        )
        paths = {file["path"] for file in merged}

        self.assertIn("requirements.txt", paths)
        self.assertTrue(any(path.startswith("src/") for path in paths))

        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            commit_files("mvpilot-generated-demo", merged, "Add scaffolded package")
            result = check_repo_health("mvpilot-generated-demo")

        self.assertEqual(result["status"], "mock")
        self.assertTrue(result["output"]["healthy"])

    def test_repo_health_passes_when_walkthrough_serves_as_demo_script(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            commit_files(
                "mvpilot-generated-walkthrough",
                [
                    {"path": "README.md", "content": "# Demo"},
                    {"path": "docs/BUILD_LOG.md", "content": "# Log"},
                    {"path": "docs/ARCHITECTURE.md", "content": "# Architecture"},
                    {"path": "docs/WALKTHROUGH.md", "content": "# Walkthrough"},
                    {"path": "package.json", "content": "{}"},
                    {"path": "src/App.jsx", "content": "export default function App(){}"},
                ],
                "Add walkthrough-only demo",
            )
            result = check_repo_health("mvpilot-generated-walkthrough")

        self.assertEqual(result["status"], "mock")
        self.assertTrue(result["output"]["healthy"])

    def test_repo_health_passes_for_complete_mock_repo(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            commit_files(
                "mvpilot-generated-demo",
                [
                    {"path": "README.md", "content": "# Demo"},
                    {"path": "logs/build_log.md", "content": "# Log"},
                    {"path": "docs/ARCHITECTURE.md", "content": "# Architecture"},
                    {"path": "demo/demo_script.md", "content": "Demo"},
                    {"path": "requirements.txt", "content": "pydantic"},
                    {"path": "src/main.py", "content": "print('hi')"},
                ],
                "Add complete scaffold",
            )
            result = check_repo_health("mvpilot-generated-demo")

        self.assertEqual(result["status"], "mock")
        self.assertTrue(result["output"]["healthy"])

    def test_repo_health_uses_supplied_task_config(self):
        config = GitHubConfig(
            token="task-token",
            owner="connected-owner",
            repo_prefix="mvpilot-generated-",
            mock_tools=False,
        )
        with (
            patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True),
            patch("tools.build_checker.GitHubClient") as client_class,
        ):
            client = client_class.return_value
            client.get_repo.return_value = {"name": "mvpilot-generated-demo"}
            client.get_contents.side_effect = [
                {"path": "README.md"},
                RuntimeError("missing docs/BUILD_LOG.md"),
                {"path": "logs/build_log.md"},
                {"path": "demo/demo_script.md"},
                RuntimeError("missing demo_script.md"),
                RuntimeError("missing docs/WALKTHROUGH.md"),
                {"path": "docs/ARCHITECTURE.md"},
                RuntimeError("missing package.json"),
                {"path": "requirements.txt"},
                {"type": "dir"},
                RuntimeError("missing backend"),
            ]

            result = check_repo_health("mvpilot-generated-demo", config=config)

        self.assertEqual(result["status"], "success")
        client_class.assert_called_once_with(config)
        self.assertTrue(result["output"]["healthy"])

    def test_repo_health_reports_missing_files(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            commit_files(
                "mvpilot-generated-demo",
                [{"path": "README.md", "content": "# Demo"}],
                "Add partial scaffold",
            )
            result = check_repo_health("mvpilot-generated-demo")

        self.assertEqual(result["status"], "failed")
        self.assertFalse(result["output"]["healthy"])
        self.assertIn("build log exists", result["output"]["missing"])


if __name__ == "__main__":
    unittest.main()
