from __future__ import annotations

import json
from typing import Any

from agent.generated_project import build_project_artifacts, merge_with_project_artifacts


PROJECT_PRIORITY_PATHS = frozenset(
    {
        "README.md",
        "src/App.jsx",
        "src/main.jsx",
        "src/styles.css",
        "src/lib/api.js",
        "src/state/projectState.js",
        "backend/main.py",
        "backend/db.py",
        "backend/models.py",
        "backend/services.py",
        "docs/ARCHITECTURE.md",
        "docs/API_SPEC.md",
        "docs/DATABASE_SCHEMA.sql",
        "docs/DEPLOY.md",
        "docs/PROJECT_PLAN.md",
        "docs/TESTING_STRATEGY.md",
    }
)


def generate_project_artifacts(
    *,
    idea: str,
    title: str | None,
    resolved_stack: str,
    architecture_plan: dict[str, Any] | None = None,
    source_warnings: list[dict[str, str]] | None = None,
    target_users: str | None = None,
    required_features: list[str] | None = None,
    tech_stack_preference: str | None = None,
    project_requirements: dict[str, Any] | None = None,
) -> list[dict[str, str]]:
    return build_project_artifacts(
        idea=idea,
        title=title,
        resolved_stack=resolved_stack,
        architecture_plan=architecture_plan,
        source_warnings=source_warnings,
        target_users=target_users,
        required_features=required_features,
        tech_stack_preference=tech_stack_preference,
        project_requirements=project_requirements,
    )


def merge_scaffold_over_model(
    artifacts: list[dict[str, Any]],
    *,
    idea: str,
    title: str | None,
    resolved_stack: str,
    architecture_plan: dict[str, Any] | None = None,
    source_warnings: list[dict[str, str]] | None = None,
    target_users: str | None = None,
    required_features: list[str] | None = None,
    tech_stack_preference: str | None = None,
    project_requirements: dict[str, Any] | None = None,
) -> list[dict[str, Any]]:
    """Prefer validated full-project files over incomplete model fragments."""

    scaffold = generate_project_artifacts(
        idea=idea,
        title=title,
        resolved_stack=resolved_stack,
        architecture_plan=architecture_plan,
        source_warnings=source_warnings,
        target_users=target_users,
        required_features=required_features,
        tech_stack_preference=tech_stack_preference,
        project_requirements=project_requirements,
    )
    by_name: dict[str, dict[str, Any]] = {}
    for artifact in artifacts:
        name = str(artifact.get("name") or "").strip()
        if name:
            by_name[name] = artifact
    for artifact in scaffold:
        name = str(artifact.get("name") or "").strip()
        if not name:
            continue
        if name in PROJECT_PRIORITY_PATHS or name not in by_name:
            by_name[name] = artifact
    return [by_name[path] for path in sorted(by_name)]


def normalize_nemotron_manifest_artifacts(
    artifacts: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Normalize Nemotron file_manifest entries without adding non-model files."""

    from agent.generated_project import _kind_from_path

    normalized: dict[str, dict[str, Any]] = {}
    for artifact in artifacts:
        name = str(artifact.get("name") or "").strip()
        if not name or name.endswith("/") or name.split("/")[-1] == ".env":
            continue
        content = artifact.get("content")
        if content is None:
            continue
        normalized[name] = {
            "name": name,
            "kind": str(artifact.get("kind") or _kind_from_path(name)),
            "summary": str(artifact.get("summary") or "Generated by Nemotron."),
            "content": content if isinstance(content, str) else json.dumps(content, indent=2),
        }
    return [normalized[path] for path in sorted(normalized)]


def hydrate_file_manifest(
    nemotron_artifacts: list[dict[str, Any]],
    *,
    idea: str,
    title: str | None,
    resolved_stack: str,
    architecture_plan: dict[str, Any] | None = None,
    source_warnings: list[dict[str, str]] | None = None,
    target_users: str | None = None,
    required_features: list[str] | None = None,
    tech_stack_preference: str | None = None,
    project_requirements: dict[str, Any] | None = None,
) -> list[dict[str, Any]]:
    """Merge Nemotron manifest metadata with complete full-project file bodies."""

    from agent.generated_project import _kind_from_path

    scaffold = generate_project_artifacts(
        idea=idea,
        title=title,
        resolved_stack=resolved_stack,
        architecture_plan=architecture_plan,
        source_warnings=source_warnings,
        target_users=target_users,
        required_features=required_features,
        tech_stack_preference=tech_stack_preference,
        project_requirements=project_requirements,
    )
    by_name: dict[str, dict[str, Any]] = {
        str(artifact["name"]): dict(artifact) for artifact in scaffold
    }
    for artifact in nemotron_artifacts:
        name = str(artifact.get("name") or "").strip()
        if not name or name.endswith("/") or name.split("/")[-1] == ".env":
            continue
        base = by_name.get(name, {})
        content = artifact.get("content")
        body = content if isinstance(content, str) and content.strip() else base.get("content")
        if body is None:
            continue
        by_name[name] = {
            "name": name,
            "kind": str(artifact.get("kind") or base.get("kind") or _kind_from_path(name)),
            "summary": str(artifact.get("summary") or base.get("summary") or "Generated by Nemotron."),
            "content": body if isinstance(body, str) else json.dumps(body, indent=2),
        }
    return [by_name[path] for path in sorted(by_name)]


def merge_model_manifest(
    artifacts: list[dict[str, Any]],
    *,
    idea: str,
    title: str | None,
    resolved_stack: str,
    architecture_plan: dict[str, Any] | None = None,
    source_warnings: list[dict[str, str]] | None = None,
    target_users: str | None = None,
    required_features: list[str] | None = None,
    tech_stack_preference: str | None = None,
    project_requirements: dict[str, Any] | None = None,
) -> list[dict[str, Any]]:
    return merge_with_project_artifacts(
        artifacts,
        idea=idea,
        title=title,
        resolved_stack=resolved_stack,
        architecture_plan=architecture_plan,
        source_warnings=source_warnings,
        target_users=target_users,
        required_features=required_features,
        tech_stack_preference=tech_stack_preference,
        project_requirements=project_requirements,
    )


def artifact_groups(artifacts: list[dict[str, Any]]) -> dict[str, list[str]]:
    groups: dict[str, list[str]] = {
        "frontend": [],
        "backend": [],
        "docs": [],
        "tests": [],
        "config": [],
    }
    for artifact in artifacts:
        name = str(artifact.get("name") or "")
        if not name:
            continue
        if name.startswith("src/") or name.endswith((".jsx", ".tsx", ".css", ".html")):
            groups["frontend"].append(name)
        elif name.startswith("backend/"):
            groups["backend"].append(name)
        elif name.startswith("docs/"):
            groups["docs"].append(name)
        elif name.startswith("tests/"):
            groups["tests"].append(name)
        else:
            groups["config"].append(name)
    return groups


# Backward-compatible alias for older tests/callers.
generate_mvp_artifacts = generate_project_artifacts
